package dal;
// Generated 3-dec-2014 14:02:54 by Hibernate Tools 4.3.1



/**
 * TblCursist generated by hbm2java
 */
public class Cursist  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String gsmnr;
     private String email;

    public Cursist() {
    }

    public Cursist(String naam, String gsmnr, String email) {
       this.naam = naam;
       this.gsmnr = gsmnr;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getGsmnr() {
        return this.gsmnr;
    }
    
    public void setGsmnr(String gsmnr) {
        this.gsmnr = gsmnr;
    }

    @Override
    public String toString() {
        return "Cursist " + naam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


