package dal;
// Generated 3-dec-2014 14:02:54 by Hibernate Tools 4.3.1



/**
 * TblDocent generated by hbm2java
 */
public class Docent  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String omschrijving;

    public Docent() {
    }

    public Docent(String naam, String omschrijving) {
       this.naam = naam;
       this.omschrijving = omschrijving;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }




}


