package dal;
// Generated 3-dec-2014 14:02:54 by Hibernate Tools 4.3.1



/**
 * TblLokaal generated by hbm2java
 */
public class Lokaal  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String gebouw;

    public Lokaal() {
    }

    public Lokaal(String naam, String gebouw) {
       this.naam = naam;
       this.gebouw = gebouw;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getGebouw() {
        return this.gebouw;
    }
    
    public void setGebouw(String gebouw) {
        this.gebouw = gebouw;
    }




}


